### ISSUE TITLE
是否可以开源服务端

### ISSUE THREAD

**Issue by Ppsj** [ErvinCheung/axshare#2]
UI界面已经开源跑起来了。但是由于没有对应的服务， 无法设置和获取密码。
不知道是否可以稍微透露一下关于服务端的相关信息？

**Comment by xelarion** [comment]
> UI界面已经开源跑起来了。但是由于没有对应的服务， 无法设置和获取密码。
> 不知道是否可以稍微透露一下关于服务端的相关信息？

https://github.com/ErvinCheung/axshare-go
简单且不完善的代码。。。。不完整的readme。。。过多的配置项。。。。
axshare-go，建议不要在docker里面运行，直接在宿主机启动，

**Comment by Ppsj** [comment]
ok,非常感谢

**Comment by ErvinCheung** [comment]
> ok,非常感谢

email： 1390838101@qq.com，如果有需要的话
